#!/usr/bin/env bash
# Takes domain and subdomain and prints 'The subdomain [] is a [] record and points to []'
if [ $# -lt 2 ]
then
	SUB=www
else
	SUB=$2
fi

TYPE=$(dig "$SUB.$1" | awk '/ANSWER S/{getline; print $4}')
IP=$(dig "$SUB.$1" | awk '/ANSWER S/{getline; print $5}')
printstuff () {
	echo "The subdomain $1 is a $2 record and points to $3"
}

printstuff "$SUB" "$TYPE" "$IP"
