#!/usr/bin/env bash
# This script transfers a file to the server via scp

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

if [ $# -ne 3 ]
then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/afile
	exit
fi

scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/afile
