#!/usr/bin/env bash
# Install nginx on an ubuntu 16.06 server

# install nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html/
sudo service nginx start

# configure default index page
echo 'Holberton School for the win!' > temp.html
sudo cp temp.html /var/www/html/index.html
rm temp.html
