#!/usr/bin/env bash
# Install nginx on an ubuntu 16.06 server with redirect

# install nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html/

# configure default index page
echo 'Holberton School for the win!' > temp.html
sudo cp temp.html /var/www/html/index.html
rm temp.html

# configure redirect
temp="\trewrite \^\/redirect_me\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n"
sudo sed -i -E "s/(^\s+location \/ \{)/$temp\1/" /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo service nginx start
