#!/usr/bin/env bash
# Installs HAproxy as a round-robin, initable load balancer for web1 and web2

sudo apt-get update
sudo apt-get install -y haproxy

myconfig="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\nbackend web_servers\n\tbalance roundrobin\n\tserver web-01 35.231.108.101 cookie web-01\n\tserver web-02 35.185.107.146 cookie web-02\n"
echo "MYPLACEHOLDER" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo sed -i -E "s/MYPLACEHOLDER/$myconfig/" /etc/haproxy/haproxy.cfg

sudo service haproxy start
