#!/usr/bin/env bash
# Installs HAproxy as a round-robin, initable load balancer for web1 and web2

sudo apt-get update
sudo apt-get install -y haproxy

existing = $(sudo cat /etc/haproxy/haproxy.cfg)
front = "frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n"
back = "backend web_servers\n\tbalance roundrobin\n\tserver web-01 35.231.108.101 cookie web-01 check\n\tserver web-02 35.185.107.146 cookie web-02 check\n"

echo "$existing $front $back"
