#!/usr/bin/env bash
# fix the bug on the server
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo kill -HUP "$(pgrep nginx -o)"
