#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely and exits with sass.
mine="1"
echo "$$" > /var/run/holbertonscript.pid
trap "echo 'y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
while [ $mine == "1" ]
do
	echo "To infinity and beyond"
	sleep 2
done


