#!/usr/bin/env bash
# This script displays a string 10 times
i="0"
while [ $i -lt 10 ]
do
  if [ "$i" == "3" ]; then
    echo "bad luck"
  elif [ "$i" == "7" ]; then
    echo "good luck"
  elif [ "1" == "1" ]; then
    echo "Holberton School"
  fi
  i=$((i+1))
done
