#!/usr/bin/env bash
# This script displays info about holbertonschool
fname="holbertonschool"
found="0"
for f in *
do
	if [ "$f" == "holbertonschool" ]; then
		found="1"
	fi
done

if [ $found == "0" ]; then
	echo "$fname file does not exist"
else
	x=$(stat -c "%F" holbertonschool)
	echo "$fname file exists"

	if [ "$(stat -c "%s" holbertonschool)" == "0" ]; then
		echo "$fname file is empty"
	else
		echo "$fname file is not empty"
	fi
	
	if [ "$(echo "$x" | cut -c-3)" == "reg" ]; then
		echo "$fname is a regular file"
	fi
fi
