#!/usr/bin/env bash
# This applies a fix to run nginx as nginx on port 8080
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sudo sed -ir "s/80 default_server/80&/" /etc/nginx/sites-available/default
kill "$(pgrep -o apache)"
sudo -u nginx nginx
